input:
  label: kafka_input
  kafka:
    addresses:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
    topics:
      - "${DEVICE_STATUS_TOPIC:topic.device.status}"
    consumer_group: "zone.dimo.export.elastic"
    client_id: ${CONTAINER_NAME:localhost}-benthos-plugin
    rack_id: ${NODE_NAME:localhost}
    commit_period: 1s
    fetch_buffer_cap: 500
    checkpoint_limit: 500
pipeline:
  threads: -1
  processors:
    - label: remove_vin
      bloblang: |
        root = this
        root.data.vin = deleted()
    - vss_vehicle:
      devices_api_grpc_addr: "localhost:3001"
    - check_signature:
    - catch:
        - log:
            message: "Processing failed due to: ${!error()}"
output:
  stdout:
    codec: lines
logger:
  level: ALL
  format: logfmt
  add_timestamp: true
